# Generated by Django 4.2 on 2023-04-22 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0002_image_created_at_image_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('capture_date', models.DateTimeField()),
                ('camera', models.CharField(max_length=80)),
                ('shutterspeed', models.CharField(max_length=10)),
                ('fnumber', models.CharField(max_length=10)),
                ('iso', models.CharField(max_length=10)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='imgapp.image')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(),
        ),
    ]
