# Generated by Django 4.2 on 2023-04-22 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0003_imagemetadata_alter_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='focallength',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='imgapp.image'),
        ),
    ]
