# Generated by Django 4.2 on 2023-04-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0004_imagemetadata_focallength_alter_imagemetadata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='lens',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
