# Generated by Django 4.2 on 2023-04-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0005_imagemetadata_lens'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_normal',
            field=models.ImageField(null=True, upload_to='image_normal'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_thumbnail',
            field=models.ImageField(null=True, upload_to='image_thumbnail'),
        ),
    ]
