# Generated by Django 4.2 on 2023-04-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0006_image_image_normal_image_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_small',
            field=models.ImageField(editable=False, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_normal',
            field=models.ImageField(editable=False, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='image'),
        ),
    ]
