# Generated by Django 4.2 on 2023-04-23 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0007_image_image_small_alter_image_image_normal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e690f446-24f8-417f-98b2-f231c7e8fd7c'), editable=False, max_length=36),
        ),
    ]
