# Generated by Django 4.2 on 2023-04-23 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0008_image_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.CharField(default=uuid.UUID('76ea41fa-db65-47b4-ac7e-951d43944b38'), editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='camera',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='fnumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='focallength',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='iso',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='lens',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='shutterspeed',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
