# Generated by Django 4.2 on 2023-04-23 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0009_alter_image_uuid_alter_imagemetadata_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.CharField(default=uuid.UUID('67207a1f-6aeb-429c-8963-65c9ea6b62aa'), editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='camera',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='fnumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='focallength',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='iso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='lens',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='shutterspeed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
