# Generated by Django 4.2 on 2023-04-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0011_daypage_alter_image_uuid_image_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daypage',
            name='day',
            field=models.DateField(unique=True),
        ),
    ]
