# Generated by Django 4.2 on 2023-04-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0012_alter_daypage_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daypage',
            name='day',
            field=models.DateField(),
        ),
    ]
