# Generated by Django 4.2 on 2023-04-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0013_alter_daypage_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
