# Generated by Django 4.2 on 2023-04-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0015_alter_image_day_alter_imagemetadata_capture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original_filename',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='shutterspeed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
