# Generated by Django 4.2 on 2023-05-02 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0017_image_height_image_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daypage',
            old_name='day',
            new_name='date',
        ),
    ]
