# Generated by Django 4.2 on 2023-06-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0018_rename_day_daypage_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='description',
        ),
    ]
