# Generated by Django 4.2 on 2024-01-04 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0019_rename_caption_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('placement', models.IntegerField(choices=[(0, 'auto'), (1, 'left'), (2, 'right'), (3, 'center')], default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgapp.album')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgapp.image')),
            ],
        ),
    ]
