# Generated by Django 4.2 on 2024-01-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0020_album_albumimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
