# Generated by Django 4.2 on 2024-01-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0022_alter_image_options_album_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='auto_left_right',
            field=models.BooleanField(default=True),
        ),
    ]
